export type FunctionKind = "pragma" | "scalar" | "table"

export type GtfsFunction = {
  name: string
  signature: string
  kind: FunctionKind
  group: string
  category: string
  description: string
  example: string
  returns: string[]
  usedByViz: boolean
  note?: string
}

export type FunctionCategory = { id: string; title: string; body: string }

export type FunctionGroup = {
  id: string
  title: string
  body: string
  categories: FunctionCategory[]
}

export const registeredCount = 89

export const internalCount = 31

export const functionGroups: FunctionGroup[] = [
  {
    id: "import",
    title: "Import",
    body: "Load a GTFS feed and manage the dataset built from it.",
    categories: [
      {
        id: "import",
        title: "Import a feed",
        body: "One call reads a GTFS folder and builds every table. GTFS Viz calls it on every import.",
      },
      {
        id: "lifecycle",
        title: "Lifecycle",
        body: "Rebuild after edits, or run the build yourself in stages. `LOAD gtfs` only registers functions.",
      },
      {
        id: "steps",
        title: "Step by step",
        body: "The steps `gtfs_import` runs, for feeds that come from somewhere other than a folder, such as a database or object storage.",
      },
    ],
  },
  {
    id: "tables",
    title: "Table functions",
    body: "Whole-feed tables: one row per station, stop, route, trip or service.",
    categories: [
      {
        id: "tables",
        title: "Table functions",
        body: "Whole-feed tables: one row per station, stop, route, trip or service, with pending edits applied.",
      },
    ],
  },
  {
    id: "gtfs",
    title: "GTFS functions",
    body: "Look up one station, pathway network, route or trip.",
    categories: [
      {
        id: "stations",
        title: "Stations",
        body: "A station's summary, its parts and the routes that serve it.",
      },
      {
        id: "pathways",
        title: "Pathways",
        body: "The pathway edges inside a station, with optional filters.",
      },
      {
        id: "pathfinding",
        title: "Pathfinding",
        body: "Graph search over a station's pathways: fastest paths, reachable parts and times between every pair of parts.",
      },
      {
        id: "routes",
        title: "Routes",
        body: "A route's details, stops, stations and shapes, and the track segments routes share.",
      },
      {
        id: "trips",
        title: "Trips",
        body: "A trip's stops, and splicing another route's stops into a trip for a reroute.",
      },
    ],
  },
  {
    id: "helpers",
    title: "Helpers",
    body: "Scalar functions for any SQL expression: GTFS times and codes to readable values.",
    categories: [
      {
        id: "helpers",
        title: "Helpers",
        body: "Scalar functions for any SQL expression: GTFS times and codes to readable values.",
      },
    ],
  },
]

export const functions: GtfsFunction[] = [
  {
    name: "gtfs_import",
    signature: "gtfs_import(directory)",
    kind: "pragma",
    group: "import",
    category: "import",
    description:
      "Import a GTFS feed from a directory in one call. It creates the edit tables, drops the previous dataset, reads each GTFS file that exists, creates empty tables for the optional ones that are missing and builds the dataset. Pending edits are kept. `stops.txt` is required. Pass `''` for files in the working directory or, in the browser, files registered by name.",
    example: "PRAGMA gtfs_import('feed');",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_prepare",
    signature: "gtfs_prepare",
    kind: "pragma",
    group: "import",
    category: "lifecycle",
    description:
      "Create the edit tables (`EditStopTable`, `EditPathwayTable`, `EditRouteTable`, `EditTripsTable`, `EditStopTimesTable`, `EditCalendarTable`, `EditCalendarDatesTable`). Run before importing.",
    example: "PRAGMA gtfs_prepare;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_init",
    signature: "gtfs_init",
    kind: "pragma",
    group: "import",
    category: "lifecycle",
    description:
      "Build the dataset's views and materialized tables (`StationsTable`, `StopsTable`, `RoutesTable`, `TripsTable`, `RouteStopsTable` and the merged `*View` views) from the imported GTFS tables.",
    example: "PRAGMA gtfs_init;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_refresh",
    signature: "gtfs_refresh",
    kind: "pragma",
    group: "import",
    category: "lifecycle",
    description:
      "Rebuild the views and tables after edits. Pending edits are kept and the imported tables are not changed.",
    example: "PRAGMA gtfs_refresh;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_drop",
    signature: "gtfs_drop",
    kind: "pragma",
    group: "import",
    category: "lifecycle",
    description: "Drop the dataset's imported tables, derived tables and views.",
    example: "PRAGMA gtfs_drop;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_add_geometry",
    signature: "gtfs_add_geometry",
    kind: "pragma",
    group: "import",
    category: "lifecycle",
    description:
      "Add a spatial `geom` point column to `stops` and `shapes`. Needs the `spatial` extension.",
    example: "PRAGMA gtfs_add_geometry;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_normalize_stops",
    signature: "gtfs_normalize_stops",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `stops` table from `stops_raw`, a table of the raw `stops.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE stops_raw AS\n  SELECT * FROM read_csv_auto('feed/stops.txt', all_varchar=true);\nPRAGMA gtfs_normalize_stops;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_pathways",
    signature: "gtfs_normalize_pathways",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `pathways` table from `pathways_raw`, a table of the raw `pathways.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE pathways_raw AS\n  SELECT * FROM read_csv_auto('feed/pathways.txt', all_varchar=true);\nPRAGMA gtfs_normalize_pathways;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_routes",
    signature: "gtfs_normalize_routes",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `routes` table from `routes_raw`, a table of the raw `routes.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE routes_raw AS\n  SELECT * FROM read_csv_auto('feed/routes.txt', all_varchar=true);\nPRAGMA gtfs_normalize_routes;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_trips",
    signature: "gtfs_normalize_trips",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `trips` table from `trips_raw`, a table of the raw `trips.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE trips_raw AS\n  SELECT * FROM read_csv_auto('feed/trips.txt', all_varchar=true);\nPRAGMA gtfs_normalize_trips;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_stop_times",
    signature: "gtfs_normalize_stop_times",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `stop_times` table from `stop_times_raw`, a table of the raw `stop_times.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE stop_times_raw AS\n  SELECT * FROM read_csv_auto('feed/stop_times.txt', all_varchar=true);\nPRAGMA gtfs_normalize_stop_times;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_shapes",
    signature: "gtfs_normalize_shapes",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `shapes` table from `shapes_raw`, a table of the raw `shapes.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE shapes_raw AS\n  SELECT * FROM read_csv_auto('feed/shapes.txt', all_varchar=true);\nPRAGMA gtfs_normalize_shapes;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_calendar",
    signature: "gtfs_normalize_calendar",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `calendar` table from `calendar_raw`, a table of the raw `calendar.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE calendar_raw AS\n  SELECT * FROM read_csv_auto('feed/calendar.txt', all_varchar=true);\nPRAGMA gtfs_normalize_calendar;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_normalize_calendar_dates",
    signature: "gtfs_normalize_calendar_dates",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create the typed `calendar_dates` table from `calendar_dates_raw`, a table of the raw `calendar_dates.txt` columns read as text. `gtfs_import` runs this for you.",
    example:
      "CREATE TABLE calendar_dates_raw AS\n  SELECT * FROM read_csv_auto('feed/calendar_dates.txt', all_varchar=true);\nPRAGMA gtfs_normalize_calendar_dates;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_pathways",
    signature: "gtfs_empty_pathways",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `pathways` table for a feed without `pathways.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_pathways;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_routes",
    signature: "gtfs_empty_routes",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `routes` table for a feed without `routes.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_routes;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_trips",
    signature: "gtfs_empty_trips",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `trips` table for a feed without `trips.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_trips;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_stop_times",
    signature: "gtfs_empty_stop_times",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `stop_times` table for a feed without `stop_times.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_stop_times;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_shapes",
    signature: "gtfs_empty_shapes",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `shapes` table for a feed without `shapes.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_shapes;",
    returns: [],
    usedByViz: false,
  },
  {
    name: "gtfs_empty_calendar",
    signature: "gtfs_empty_calendar",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `calendar` table for a feed without `calendar.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_calendar;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "gtfs_empty_calendar_dates",
    signature: "gtfs_empty_calendar_dates",
    kind: "pragma",
    group: "import",
    category: "steps",
    description:
      "Create an empty `calendar_dates` table for a feed without `calendar_dates.txt`. `gtfs_import` runs this for you.",
    example: "PRAGMA gtfs_empty_calendar_dates;",
    returns: [],
    usedByViz: true,
  },
  {
    name: "get_gtfs_data_availability",
    signature: "get_gtfs_data_availability()",
    kind: "table",
    group: "tables",
    category: "tables",
    description:
      "Row counts for stations, stops, pathways, routes and trips, and which dashboard views have data.",
    example: "SELECT * FROM get_gtfs_data_availability();",
    returns: [
      "stations",
      "stops",
      "pathways",
      "routes",
      "trips",
      "has_stations",
      "has_stops",
      "has_routes",
      "has_trips",
    ],
    usedByViz: true,
  },
  {
    name: "get_stations_table_data",
    signature: "get_stations_table_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description:
      "Every station with exit count, pathway status, wheelchair status and the routes that serve it.",
    example: "SELECT * FROM get_stations_table_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "exit_count",
      "location_type_name",
      "parent_station",
      "wheelchair_status",
      "route_count",
      "route_links",
      "pathways_status",
    ],
    usedByViz: true,
  },
  {
    name: "get_stops_table_data",
    signature: "get_stops_table_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description: "Every standalone stop (no parent station) with the routes that serve it.",
    example: "SELECT * FROM get_stops_table_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "route_count",
      "route_links",
    ],
    usedByViz: true,
    note: "Empty for feeds where every stop belongs to a station, such as the MBTA subway.",
  },
  {
    name: "get_stops_view_data",
    signature: "get_stops_view_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description: "Every stop and station part from `StopsView`, including pending edits.",
    example: "SELECT * FROM get_stops_view_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "status",
    ],
    usedByViz: false,
  },
  {
    name: "get_routes_table_data",
    signature: "get_routes_table_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description: "Every route with its stop, station and trip counts and colours.",
    example: "SELECT * FROM get_routes_table_data();",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_trips_table_data",
    signature: "get_trips_table_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description: "Every trip with first departure, last arrival and stop count.",
    example: "SELECT * FROM get_trips_table_data();",
    returns: [
      "trip_id",
      "route_id",
      "service_id",
      "trip_headsign",
      "trip_short_name",
      "direction_id",
      "block_id",
      "shape_id",
      "route_name",
      "route_type_name",
      "route_color_hex",
      "first_departure_seconds",
      "last_arrival_seconds",
    ],
    usedByViz: true,
  },
  {
    name: "get_calendar_table_data",
    signature: "get_calendar_table_data()",
    kind: "table",
    group: "tables",
    category: "tables",
    description: "Every service in `calendar`, including pending edits.",
    example: "SELECT * FROM get_calendar_table_data();",
    returns: [
      "service_id",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
      "sunday",
      "start_date",
      "end_date",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_station_info",
    signature: "get_station_info(station_id)",
    kind: "table",
    group: "gtfs",
    category: "stations",
    description: "One station's summary: location, exit count, pathway count and pathway status.",
    example: "SELECT * FROM get_station_info('place-pktrm');",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "exit_count",
      "location_type_name",
      "parent_station",
      "wheelchair_status",
      "pathway_count",
      "route_count",
      "route_links",
      "pathways_status",
    ],
    usedByViz: true,
  },
  {
    name: "get_station_stops",
    signature: "get_station_stops(station_id)",
    kind: "table",
    group: "gtfs",
    category: "stations",
    description:
      "All parts of a station (platforms, entrances, pathway nodes, boarding areas), including new ones from edits.",
    example: "SELECT * FROM get_station_stops('place-pktrm');",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_station_service_routes",
    signature: "get_station_service_routes(p_station_id)",
    kind: "table",
    group: "gtfs",
    category: "stations",
    description: "Routes that stop at a station.",
    example: "SELECT * FROM get_station_service_routes('place-pktrm');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_stop_service_routes",
    signature: "get_stop_service_routes(p_stop_id)",
    kind: "table",
    group: "gtfs",
    category: "stations",
    description: "Routes that stop at a stop or platform.",
    example: "SELECT * FROM get_stop_service_routes('70075');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_station_pathways",
    signature: "get_station_pathways(station_id)",
    kind: "table",
    group: "gtfs",
    category: "pathways",
    description:
      "Every pathway in a station with endpoints, coordinates, mode, direction and angle, including edits.",
    example: "SELECT * FROM get_station_pathways('place-pktrm');",
    returns: [
      "row_id",
      "pathway_id",
      "from_stop_id",
      "to_stop_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "traversal_time",
      "length",
      "stair_count",
      "max_slope",
      "min_width",
      "signposted_as",
      "reversed_signposted_as",
      "pathway_mode_name",
      "pathway_mode",
      "direction_type",
      "is_bidirectional",
      "status",
      "from_location_type_name",
      "to_location_type_name",
      "from_parent_station",
      "to_parent_station",
      "angle",
    ],
    usedByViz: true,
  },
  {
    name: "get_station_connections",
    signature: "get_station_connections(station_id)",
    kind: "table",
    group: "gtfs",
    category: "pathways",
    description:
      "Directed connection graph with stop names and time periods, used by the Flow view.",
    example: "SELECT * FROM get_station_connections('place-pktrm');",
    returns: [
      "pathway_id",
      "from_stop_id",
      "from_stop_name",
      "from_location_type_name",
      "to_stop_id",
      "to_stop_name",
      "to_location_type_name",
      "traversal_time_seconds",
      "time_period",
      "length",
      "pathway_mode_name",
      "direction_type",
      "is_bidirectional",
      "edge_direction",
      "angle",
    ],
    usedByViz: true,
  },
  {
    name: "get_pathways_filtered",
    signature:
      "get_pathways_filtered(station_id, to_stop, from_stop, min_time, max_time, include_null_time, direction_filter, pathway_types)",
    kind: "table",
    group: "gtfs",
    category: "pathways",
    description: "Pathways that match optional filters. Pass `NULL` to skip a filter.",
    example:
      "SELECT * FROM get_pathways_filtered('place-pktrm', NULL, NULL, 0, 120, TRUE, NULL, NULL);",
    returns: [
      "pathway_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "from_stop_id",
      "to_stop_id",
      "traversal_time",
      "pathway_mode_name",
      "direction_type",
      "angle",
    ],
    usedByViz: true,
  },
  {
    name: "get_direct_pathways",
    signature:
      "get_direct_pathways(p_station_id, from_stop := NULL, to_stop := NULL, direction_filter := NULL, pathway_types := NULL)",
    kind: "table",
    group: "gtfs",
    category: "pathways",
    description:
      "Single-hop pathways between station parts, with optional endpoint, direction and mode filters.",
    example: "SELECT * FROM get_direct_pathways('place-pktrm');",
    returns: [
      "pathway_id",
      "from_stop_id",
      "to_stop_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "traversal_time",
      "pathway_mode_name",
      "pathway_mode",
      "direction_type",
      "is_bidirectional",
    ],
    usedByViz: true,
  },
  {
    name: "find_shortest_path",
    signature: "find_shortest_path(p_station_id, start_stop, end_stop, max_hops := 10)",
    kind: "table",
    group: "gtfs",
    category: "pathfinding",
    description:
      "Fastest path between two station parts, with total time, hops and the pathway ids.",
    example:
      "SELECT current_stop, destination, total_time, hop_count\n  FROM find_shortest_path('place-pktrm', 'door-pktrm-elevatorwb', '70075', 10);",
    returns: [
      "current_stop",
      "destination",
      "total_time",
      "hop_count",
      "path_ids",
      "visited_stops",
      "path_description",
    ],
    usedByViz: true,
  },
  {
    name: "find_reachable_stops",
    signature: "find_reachable_stops(p_station_id, start_stop, max_time := NULL, max_hops := 5)",
    kind: "table",
    group: "gtfs",
    category: "pathfinding",
    description: "Every station part reachable from a start within a time and hop limit.",
    example: "SELECT * FROM find_reachable_stops('place-pktrm', 'door-pktrm-elevatorwb', 120, 3);",
    returns: ["reachable_stop", "min_time", "min_hops"],
    usedByViz: true,
  },
  {
    name: "find_all_paths",
    signature: "find_all_paths(p_station_id, start_stop, end_stop, max_hops := 5)",
    kind: "table",
    group: "gtfs",
    category: "pathfinding",
    description: "Every path between two station parts up to a hop limit, not only the fastest.",
    example: "SELECT * FROM find_all_paths('place-pktrm', 'door-pktrm-elevatorwb', '70075', 7);",
    returns: ["total_time", "hop_count", "path_ids", "route"],
    usedByViz: true,
  },
  {
    name: "get_station_routes",
    signature: "get_station_routes(p_station_id)",
    kind: "table",
    group: "gtfs",
    category: "pathfinding",
    description:
      "Shortest time between every reachable pair of station parts, behind the station Route view. Use it to find platforms that cannot reach an exit.",
    example: "SELECT * FROM get_station_routes('place-pktrm');",
    returns: [
      "start_stop",
      "end_stop",
      "shortest_time",
      "from_location_type_name",
      "to_location_type_name",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_info",
    signature: "get_route_info(p_route_id)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "One route from `RoutesTable`.",
    example: "SELECT * FROM get_route_info('Red');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_stops",
    signature: "get_route_stops(p_route_id)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "A route's stops in stop-sequence order, with their stations.",
    example: "SELECT * FROM get_route_stops('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "station_id",
      "station_name",
      "stop_sequence",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_stations",
    signature: "get_route_stations(p_route_id)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "Distinct stations a route serves, with coordinates.",
    example: "SELECT * FROM get_route_stations('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "station_id",
      "station_name",
      "stop_lat",
      "stop_lon",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_shapes",
    signature: "get_route_shapes(p_route_id)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "Shape points for a route.",
    example: "SELECT * FROM get_route_shapes('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_lat",
      "shape_pt_lon",
      "shape_pt_sequence",
      "shape_dist_traveled",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_stops_for_routes",
    signature: "get_route_stops_for_routes(p_route_ids)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "Stops for a list of routes.",
    example: "SELECT * FROM get_route_stops_for_routes(['Red', 'Orange']);",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "station_id",
      "station_name",
      "stop_sequence",
    ],
    usedByViz: true,
  },
  {
    name: "get_route_shapes_for_routes",
    signature: "get_route_shapes_for_routes(p_route_ids)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "Shape points for a list of routes.",
    example: "SELECT * FROM get_route_shapes_for_routes(['Red', 'Orange']);",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_lat",
      "shape_pt_lon",
      "shape_pt_sequence",
      "shape_dist_traveled",
    ],
    usedByViz: false,
  },
  {
    name: "get_route_corridors",
    signature: "get_route_corridors(p_route_ids, snap_precision := 4)",
    kind: "table",
    group: "gtfs",
    category: "routes",
    description: "Shape segments that two or more of the given routes share.",
    example: "SELECT * FROM get_route_corridors(['Green-B', 'Green-C', 'Green-D', 'Green-E']);",
    returns: ["corridor_key", "route_id", "band_index", "band_count"],
    usedByViz: false,
  },
  {
    name: "get_trip_stops",
    signature: "get_trip_stops(p_trip_id, p_remove_names, p_first_name, p_last_name)",
    kind: "table",
    group: "gtfs",
    category: "trips",
    description:
      "A trip's stops with times, optionally dropping named stops or cutting it to a first and last stop.",
    example: "SELECT * FROM get_trip_stops('canonical-Red-C1-0', [], NULL, NULL);",
    returns: ["stop_sequence", "stop_id", "arrival_time", "departure_time"],
    usedByViz: true,
  },
  {
    name: "get_trip_reroute_routes",
    signature: "get_trip_reroute_routes(p_trip_id)",
    kind: "table",
    group: "gtfs",
    category: "trips",
    description:
      "Routes with a donor trip whose stops differ from the trip between at least two shared stations.",
    example: "SELECT * FROM get_trip_reroute_routes('canonical-Green-B-C1-0');",
    returns: [
      "route_id",
      "route_name",
      "route_short_name",
      "route_type_name",
      "route_color_hex",
      "donor_trip_id",
      "shared_station_count",
    ],
    usedByViz: true,
  },
  {
    name: "get_trip_reroute_boundary_pairs",
    signature: "get_trip_reroute_boundary_pairs(p_trip_id, p_donor_trip_id)",
    kind: "table",
    group: "gtfs",
    category: "trips",
    description:
      "Shared station pairs between which the trip and the donor stop at different places.",
    example:
      "SELECT * FROM get_trip_reroute_boundary_pairs('canonical-Green-B-C1-0', 'canonical-Green-D-C1-0');",
    returns: [
      "from_station",
      "to_station",
      "affected_from_sequence",
      "affected_to_sequence",
      "donor_from_sequence",
      "donor_to_sequence",
    ],
    usedByViz: true,
  },
  {
    name: "get_reroute_stop_times",
    signature: "get_reroute_stop_times(p_trip_id, p_donor_trip_id, p_from_name, p_to_name)",
    kind: "table",
    group: "gtfs",
    category: "trips",
    description:
      "The trip with the section between two stations replaced by the donor's stops, timing scaled into the trip's window.",
    example:
      "SELECT * FROM get_reroute_stop_times('canonical-Green-B-C1-0', 'canonical-Green-D-C1-0', 'Government Center', 'Copley');",
    returns: ["stop_sequence", "stop_id", "arrival_time", "departure_time"],
    usedByViz: true,
  },
  {
    name: "gtfs_time_to_seconds",
    signature: "gtfs_time_to_seconds(t)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description: "GTFS time (`HH:MM:SS`, hours can pass 24) to seconds after midnight.",
    example: "SELECT gtfs_time_to_seconds('25:15:00');",
    returns: ["90900"],
    usedByViz: false,
  },
  {
    name: "seconds_to_gtfs_time",
    signature: "seconds_to_gtfs_time(s)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description: "Seconds after midnight to a GTFS time string.",
    example: "SELECT seconds_to_gtfs_time(90900);",
    returns: ["25:15:00"],
    usedByViz: false,
  },
  {
    name: "location_type_to_name",
    signature: "location_type_to_name(location_type, parent_station)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description:
      "GTFS `location_type` to a name: Stop, Platform, Station, Exit/Entrance, Pathway Node or Boarding Area. A stop with a parent station is a Platform.",
    example: "SELECT location_type_to_name(0, 'place-pktrm');",
    returns: ["Platform"],
    usedByViz: false,
  },
  {
    name: "pathway_mode_to_name",
    signature: "pathway_mode_to_name(mode)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description:
      "GTFS `pathway_mode` to a name: Walkway, Stairs, Moving sidewalk/travelator, Escalator, Elevator, Fare gate or Exit gate.",
    example: "SELECT pathway_mode_to_name(5);",
    returns: ["Elevator"],
    usedByViz: false,
  },
  {
    name: "bidirectional_to_direction",
    signature: "bidirectional_to_direction(is_bidirectional)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description: "`is_bidirectional` to `directional` or `bidirectional`.",
    example: "SELECT bidirectional_to_direction(1);",
    returns: ["bidirectional"],
    usedByViz: false,
  },
  {
    name: "route_type_to_name",
    signature: "route_type_to_name(route_type)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description: "GTFS `route_type`, including extended types, to a name.",
    example: "SELECT route_type_to_name(1);",
    returns: ["Subway, Metro"],
    usedByViz: false,
  },
  {
    name: "gtfs_color_to_hex",
    signature: "gtfs_color_to_hex(color_value, fallback_value)",
    kind: "scalar",
    group: "helpers",
    category: "helpers",
    description: "A GTFS colour such as `DA291C` to `#DA291C`, or the fallback when it is empty.",
    example: "SELECT gtfs_color_to_hex('DA291C', '#000000');",
    returns: ["#DA291C"],
    usedByViz: false,
  },
]
