export type FunctionKind = "pragma" | "scalar" | "table"

export type GtfsFunction = {
  name: string
  signature: string
  kind: FunctionKind
  category: string
  description: string
  example: string
  returns: string[]
  note?: string
}

export const functionCategories = [
  {
    id: "lifecycle",
    title: "Lifecycle",
    body: "Pragmas that create, rebuild and drop a dataset. `LOAD gtfs` only registers functions; these do the work.",
  },
  {
    id: "import",
    title: "Import",
    body: "Turn raw GTFS CSV tables into typed tables. Load each file into `<table>_raw` first, then run the matching pragma.",
  },
  {
    id: "route-cache",
    title: "Route cache",
    body: "Manage the tables that hold route-band geometry.",
  },
  {
    id: "scalar",
    title: "Scalar helpers",
    body: "Small conversions usable in any SQL expression.",
  },
  {
    id: "dataset",
    title: "Dataset tables",
    body: "Whole-feed tables behind the web app's tables and the CLI's list commands.",
  },
  {
    id: "stations",
    title: "Stations and stops",
    body: "Station summaries, station parts and the routes that serve them.",
  },
  {
    id: "pathways",
    title: "Pathways",
    body: "Pathway edges inside a station and the filters the pathway views use.",
  },
  { id: "pathfinding", title: "Pathfinding", body: "Routes through a station's pathway graph." },
  { id: "routes", title: "Routes", body: "Route details, stops, stations and shapes." },
  { id: "bounds", title: "Map bounds", body: "Bounding box, centre and zoom for map views." },
  {
    id: "bands",
    title: "Route bands",
    body: "Parallel route-line geometry for routes that share track, built from GTFS shapes alone.",
  },
  {
    id: "trips",
    title: "Trips and rerouting",
    body: "Trip stop lists and splicing another route's stops into a trip.",
  },
]

export const functions: GtfsFunction[] = [
  {
    name: "gtfs_prepare",
    signature: "gtfs_prepare",
    kind: "pragma",
    category: "lifecycle",
    description:
      "Create the edit tables (`EditStopTable`, `EditPathwayTable`, `EditRouteTable`, `EditTripsTable`, `EditStopTimesTable`, `EditCalendarTable`, `EditCalendarDatesTable`). Run before importing.",
    example: "PRAGMA gtfs_prepare;",
    returns: [],
  },
  {
    name: "gtfs_init",
    signature: "gtfs_init",
    kind: "pragma",
    category: "lifecycle",
    description:
      "Build the dataset's views and materialized tables (`StationsTable`, `StopsTable`, `RoutesTable`, `TripsTable`, `RouteStopsTable` and the merged `*View` views) from the imported GTFS tables.",
    example: "PRAGMA gtfs_init;",
    returns: [],
  },
  {
    name: "gtfs_refresh",
    signature: "gtfs_refresh",
    kind: "pragma",
    category: "lifecycle",
    description:
      "Rebuild the views and tables after edits. Pending edits are kept and the imported tables are not changed.",
    example: "PRAGMA gtfs_refresh;",
    returns: [],
  },
  {
    name: "gtfs_drop",
    signature: "gtfs_drop",
    kind: "pragma",
    category: "lifecycle",
    description: "Drop the dataset's imported tables, derived tables and views.",
    example: "PRAGMA gtfs_drop;",
    returns: [],
  },
  {
    name: "gtfs_add_geometry",
    signature: "gtfs_add_geometry",
    kind: "pragma",
    category: "lifecycle",
    description:
      "Add a spatial `geom` point column to `stops` and `shapes`. Needs the `spatial` extension.",
    example: "PRAGMA gtfs_add_geometry;",
    returns: [],
  },
  {
    name: "gtfs_normalize_stops",
    signature: "gtfs_normalize_stops",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `stops` table from `stops_raw`, a table of the raw `stops.txt` columns read as text.",
    example:
      "CREATE TABLE stops_raw AS\n  SELECT * FROM read_csv_auto('feed/stops.txt', all_varchar=true);\nPRAGMA gtfs_normalize_stops;",
    returns: [],
  },
  {
    name: "gtfs_normalize_pathways",
    signature: "gtfs_normalize_pathways",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `pathways` table from `pathways_raw`, a table of the raw `pathways.txt` columns read as text.",
    example:
      "CREATE TABLE pathways_raw AS\n  SELECT * FROM read_csv_auto('feed/pathways.txt', all_varchar=true);\nPRAGMA gtfs_normalize_pathways;",
    returns: [],
  },
  {
    name: "gtfs_normalize_routes",
    signature: "gtfs_normalize_routes",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `routes` table from `routes_raw`, a table of the raw `routes.txt` columns read as text.",
    example:
      "CREATE TABLE routes_raw AS\n  SELECT * FROM read_csv_auto('feed/routes.txt', all_varchar=true);\nPRAGMA gtfs_normalize_routes;",
    returns: [],
  },
  {
    name: "gtfs_normalize_trips",
    signature: "gtfs_normalize_trips",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `trips` table from `trips_raw`, a table of the raw `trips.txt` columns read as text.",
    example:
      "CREATE TABLE trips_raw AS\n  SELECT * FROM read_csv_auto('feed/trips.txt', all_varchar=true);\nPRAGMA gtfs_normalize_trips;",
    returns: [],
  },
  {
    name: "gtfs_normalize_stop_times",
    signature: "gtfs_normalize_stop_times",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `stop_times` table from `stop_times_raw`, a table of the raw `stop_times.txt` columns read as text.",
    example:
      "CREATE TABLE stop_times_raw AS\n  SELECT * FROM read_csv_auto('feed/stop_times.txt', all_varchar=true);\nPRAGMA gtfs_normalize_stop_times;",
    returns: [],
  },
  {
    name: "gtfs_normalize_shapes",
    signature: "gtfs_normalize_shapes",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `shapes` table from `shapes_raw`, a table of the raw `shapes.txt` columns read as text.",
    example:
      "CREATE TABLE shapes_raw AS\n  SELECT * FROM read_csv_auto('feed/shapes.txt', all_varchar=true);\nPRAGMA gtfs_normalize_shapes;",
    returns: [],
  },
  {
    name: "gtfs_normalize_calendar",
    signature: "gtfs_normalize_calendar",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `calendar` table from `calendar_raw`, a table of the raw `calendar.txt` columns read as text.",
    example:
      "CREATE TABLE calendar_raw AS\n  SELECT * FROM read_csv_auto('feed/calendar.txt', all_varchar=true);\nPRAGMA gtfs_normalize_calendar;",
    returns: [],
  },
  {
    name: "gtfs_normalize_calendar_dates",
    signature: "gtfs_normalize_calendar_dates",
    kind: "pragma",
    category: "import",
    description:
      "Create the typed `calendar_dates` table from `calendar_dates_raw`, a table of the raw `calendar_dates.txt` columns read as text.",
    example:
      "CREATE TABLE calendar_dates_raw AS\n  SELECT * FROM read_csv_auto('feed/calendar_dates.txt', all_varchar=true);\nPRAGMA gtfs_normalize_calendar_dates;",
    returns: [],
  },
  {
    name: "gtfs_empty_pathways",
    signature: "gtfs_empty_pathways",
    kind: "pragma",
    category: "import",
    description: "Create an empty `pathways` table for a feed without `pathways.txt`.",
    example: "PRAGMA gtfs_empty_pathways;",
    returns: [],
  },
  {
    name: "gtfs_empty_routes",
    signature: "gtfs_empty_routes",
    kind: "pragma",
    category: "import",
    description: "Create an empty `routes` table for a feed without `routes.txt`.",
    example: "PRAGMA gtfs_empty_routes;",
    returns: [],
  },
  {
    name: "gtfs_empty_trips",
    signature: "gtfs_empty_trips",
    kind: "pragma",
    category: "import",
    description: "Create an empty `trips` table for a feed without `trips.txt`.",
    example: "PRAGMA gtfs_empty_trips;",
    returns: [],
  },
  {
    name: "gtfs_empty_stop_times",
    signature: "gtfs_empty_stop_times",
    kind: "pragma",
    category: "import",
    description: "Create an empty `stop_times` table for a feed without `stop_times.txt`.",
    example: "PRAGMA gtfs_empty_stop_times;",
    returns: [],
  },
  {
    name: "gtfs_empty_shapes",
    signature: "gtfs_empty_shapes",
    kind: "pragma",
    category: "import",
    description: "Create an empty `shapes` table for a feed without `shapes.txt`.",
    example: "PRAGMA gtfs_empty_shapes;",
    returns: [],
  },
  {
    name: "gtfs_empty_calendar",
    signature: "gtfs_empty_calendar",
    kind: "pragma",
    category: "import",
    description: "Create an empty `calendar` table for a feed without `calendar.txt`.",
    example: "PRAGMA gtfs_empty_calendar;",
    returns: [],
  },
  {
    name: "gtfs_empty_calendar_dates",
    signature: "gtfs_empty_calendar_dates",
    kind: "pragma",
    category: "import",
    description: "Create an empty `calendar_dates` table for a feed without `calendar_dates.txt`.",
    example: "PRAGMA gtfs_empty_calendar_dates;",
    returns: [],
  },
  {
    name: "gtfs_prepare_route_cache",
    signature: "gtfs_prepare_route_cache",
    kind: "pragma",
    category: "route-cache",
    description:
      "Create `RouteShapeLanesTable`, `RouteShapeBandsTable` and `RouteShapeMacroVersion` if they do not exist.",
    example: "PRAGMA gtfs_prepare_route_cache;",
    returns: [],
  },
  {
    name: "gtfs_reset_route_cache",
    signature: "gtfs_reset_route_cache",
    kind: "pragma",
    category: "route-cache",
    description: "Drop and recreate the route-band tables, clearing any built bands.",
    example: "PRAGMA gtfs_reset_route_cache;",
    returns: [],
  },
  {
    name: "gtfs_route_cache_version",
    signature: "gtfs_route_cache_version",
    kind: "pragma",
    category: "route-cache",
    description:
      "Return the route-band macro version. Clients store it in `RouteShapeMacroVersion` to know when built bands are stale.",
    example: "PRAGMA gtfs_route_cache_version;",
    returns: [],
  },
  {
    name: "gtfs_time_to_seconds",
    signature: "gtfs_time_to_seconds(t)",
    kind: "scalar",
    category: "scalar",
    description: "GTFS time (`HH:MM:SS`, hours can pass 24) to seconds after midnight.",
    example: "SELECT gtfs_time_to_seconds('25:15:00');",
    returns: ["90900"],
  },
  {
    name: "seconds_to_gtfs_time",
    signature: "seconds_to_gtfs_time(s)",
    kind: "scalar",
    category: "scalar",
    description: "Seconds after midnight to a GTFS time string.",
    example: "SELECT seconds_to_gtfs_time(90900);",
    returns: ["25:15:00"],
  },
  {
    name: "location_type_to_name",
    signature: "location_type_to_name(location_type, parent_station)",
    kind: "scalar",
    category: "scalar",
    description:
      "GTFS `location_type` to a name: Stop, Platform, Station, Exit/Entrance, Pathway Node or Boarding Area. A stop with a parent station is a Platform.",
    example: "SELECT location_type_to_name(0, 'place-pktrm');",
    returns: ["Platform"],
  },
  {
    name: "pathway_mode_to_name",
    signature: "pathway_mode_to_name(mode)",
    kind: "scalar",
    category: "scalar",
    description:
      "GTFS `pathway_mode` to a name: Walkway, Stairs, Moving sidewalk/travelator, Escalator, Elevator, Fare gate or Exit gate.",
    example: "SELECT pathway_mode_to_name(5);",
    returns: ["Elevator"],
  },
  {
    name: "wheelchair_to_emoji",
    signature: "wheelchair_to_emoji(wheelchair_boarding)",
    kind: "scalar",
    category: "scalar",
    description:
      "`wheelchair_boarding` to a status dot: 🔵 no information, 🟢 accessible, 🔴 not accessible.",
    example: "SELECT wheelchair_to_emoji(1);",
    returns: ["🟢"],
  },
  {
    name: "bidirectional_to_direction",
    signature: "bidirectional_to_direction(is_bidirectional)",
    kind: "scalar",
    category: "scalar",
    description: "`is_bidirectional` to `directional` or `bidirectional`.",
    example: "SELECT bidirectional_to_direction(1);",
    returns: ["bidirectional"],
  },
  {
    name: "route_type_to_name",
    signature: "route_type_to_name(route_type)",
    kind: "scalar",
    category: "scalar",
    description: "GTFS `route_type`, including extended types, to a name.",
    example: "SELECT route_type_to_name(1);",
    returns: ["Subway, Metro"],
  },
  {
    name: "gtfs_color_to_hex",
    signature: "gtfs_color_to_hex(color_value, fallback_value)",
    kind: "scalar",
    category: "scalar",
    description: "A GTFS colour such as `DA291C` to `#DA291C`, or the fallback when it is empty.",
    example: "SELECT gtfs_color_to_hex('DA291C', '#000000');",
    returns: ["#DA291C"],
  },
  {
    name: "fit_zoom",
    signature: "fit_zoom(min_lon, max_lon, min_lat, max_lat)",
    kind: "scalar",
    category: "scalar",
    description: "Web Mercator zoom level (4 to 17) that fits a bounding box.",
    example: "SELECT fit_zoom(-71.2, -71.0, 42.3, 42.4);",
    returns: ["11.0"],
  },
  {
    name: "route_band_offset_deg",
    signature: "route_band_offset_deg(band_index, band_count, spacing_meters)",
    kind: "scalar",
    category: "scalar",
    description: "Lateral offset in degrees for one band in a bundle of parallel route lines.",
    example: "SELECT route_band_offset_deg(0, 3, 16.0);",
    returns: ["-0.00014372978799856272"],
  },
  {
    name: "get_gtfs_data_availability",
    signature: "get_gtfs_data_availability()",
    kind: "table",
    category: "dataset",
    description:
      "Row counts for stations, stops, pathways, routes and trips, and which dashboard views have data.",
    example: "SELECT * FROM get_gtfs_data_availability();",
    returns: [
      "stations",
      "stops",
      "pathways",
      "routes",
      "trips",
      "has_stations",
      "has_stops",
      "has_routes",
      "has_trips",
    ],
  },
  {
    name: "get_stations_table_data",
    signature: "get_stations_table_data()",
    kind: "table",
    category: "dataset",
    description:
      "Every station with exit count, pathway status, wheelchair status and the routes that serve it.",
    example: "SELECT * FROM get_stations_table_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "exit_count",
      "location_type_name",
      "parent_station",
      "wheelchair_status",
      "route_count",
      "route_links",
      "pathways_status",
    ],
  },
  {
    name: "get_stops_table_data",
    signature: "get_stops_table_data()",
    kind: "table",
    category: "dataset",
    description: "Every standalone stop (no parent station) with the routes that serve it.",
    example: "SELECT * FROM get_stops_table_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "route_count",
      "route_links",
    ],
    note: "Empty for feeds where every stop belongs to a station, such as the MBTA subway.",
  },
  {
    name: "get_stops_view_data",
    signature: "get_stops_view_data()",
    kind: "table",
    category: "dataset",
    description: "Every stop and station part from `StopsView`, including pending edits.",
    example: "SELECT * FROM get_stops_view_data();",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "status",
    ],
  },
  {
    name: "get_routes_table_data",
    signature: "get_routes_table_data()",
    kind: "table",
    category: "dataset",
    description: "Every route with its stop, station and trip counts and colours.",
    example: "SELECT * FROM get_routes_table_data();",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
  },
  {
    name: "get_trips_table_data",
    signature: "get_trips_table_data()",
    kind: "table",
    category: "dataset",
    description: "Every trip with first departure, last arrival and stop count.",
    example: "SELECT * FROM get_trips_table_data();",
    returns: [
      "trip_id",
      "route_id",
      "service_id",
      "trip_headsign",
      "trip_short_name",
      "direction_id",
      "block_id",
      "shape_id",
      "route_name",
      "route_type_name",
      "route_color_hex",
      "first_departure_seconds",
      "last_arrival_seconds",
    ],
  },
  {
    name: "get_calendar_table_data",
    signature: "get_calendar_table_data()",
    kind: "table",
    category: "dataset",
    description: "Every service in `calendar`, including pending edits.",
    example: "SELECT * FROM get_calendar_table_data();",
    returns: [
      "service_id",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
      "sunday",
      "start_date",
      "end_date",
      "status",
    ],
  },
  {
    name: "get_trips_time_bounds",
    signature: "get_trips_time_bounds()",
    kind: "table",
    category: "dataset",
    description:
      "Earliest departure and latest arrival across all trips, rounded to 5 minutes, in seconds.",
    example: "SELECT * FROM get_trips_time_bounds();",
    returns: ["min_time", "max_time"],
  },
  {
    name: "get_station_info",
    signature: "get_station_info(station_id)",
    kind: "table",
    category: "stations",
    description: "One station's summary: location, exit count, pathway count and pathway status.",
    example: "SELECT * FROM get_station_info('place-pktrm');",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "status",
      "exit_count",
      "location_type_name",
      "parent_station",
      "wheelchair_status",
      "pathway_count",
      "route_count",
      "route_links",
      "pathways_status",
    ],
  },
  {
    name: "get_station_stops",
    signature: "get_station_stops(station_id)",
    kind: "table",
    category: "stations",
    description:
      "All parts of a station (platforms, entrances, pathway nodes, boarding areas), including new ones from edits.",
    example: "SELECT * FROM get_station_stops('place-pktrm');",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "level_id",
      "wheelchair_status",
      "status",
    ],
  },
  {
    name: "get_station_stops_for_pathways",
    signature: "get_station_stops_for_pathways(station_id)",
    kind: "table",
    category: "stations",
    description: "Rows from `stops` whose parent is the station, with every GTFS column.",
    example: "SELECT * FROM get_station_stops_for_pathways('place-pktrm');",
    returns: [
      "row_id",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "parent_station",
      "location_type",
      "wheelchair_boarding",
      "stop_code",
      "stop_desc",
      "platform_code",
      "platform_name",
      "zone_id",
      "stop_address",
      "stop_url",
      "level_id",
      "municipality",
      "on_street",
      "at_street",
      "vehicle_type",
      "location_type_name",
      "wheelchair_status",
    ],
  },
  {
    name: "get_station_service_routes",
    signature: "get_station_service_routes(p_station_id)",
    kind: "table",
    category: "stations",
    description: "Routes that stop at a station.",
    example: "SELECT * FROM get_station_service_routes('place-pktrm');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
  },
  {
    name: "get_stop_service_routes",
    signature: "get_stop_service_routes(p_stop_id)",
    kind: "table",
    category: "stations",
    description: "Routes that stop at a stop or platform.",
    example: "SELECT * FROM get_stop_service_routes('70075');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
  },
  {
    name: "get_station_pathways",
    signature: "get_station_pathways(station_id)",
    kind: "table",
    category: "pathways",
    description:
      "Every pathway in a station with endpoints, coordinates, mode, direction and angle, including edits.",
    example: "SELECT * FROM get_station_pathways('place-pktrm');",
    returns: [
      "row_id",
      "pathway_id",
      "from_stop_id",
      "to_stop_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "traversal_time",
      "length",
      "stair_count",
      "max_slope",
      "min_width",
      "signposted_as",
      "reversed_signposted_as",
      "pathway_mode_name",
      "pathway_mode",
      "direction_type",
      "is_bidirectional",
      "status",
      "from_location_type_name",
      "to_location_type_name",
      "from_parent_station",
      "to_parent_station",
      "angle",
    ],
  },
  {
    name: "get_station_connections",
    signature: "get_station_connections(station_id)",
    kind: "table",
    category: "pathways",
    description:
      "Directed connection graph with stop names and time periods, used by the Flow view.",
    example: "SELECT * FROM get_station_connections('place-pktrm');",
    returns: [
      "pathway_id",
      "from_stop_id",
      "from_stop_name",
      "from_location_type_name",
      "to_stop_id",
      "to_stop_name",
      "to_location_type_name",
      "traversal_time_seconds",
      "time_period",
      "length",
      "pathway_mode_name",
      "direction_type",
      "is_bidirectional",
      "edge_direction",
      "angle",
    ],
  },
  {
    name: "get_all_pathway_aggregates",
    signature: "get_all_pathway_aggregates(station_id)",
    kind: "table",
    category: "pathways",
    description:
      "One row listing a station's from-stops, to-stops, modes, direction types and time range, for filter menus.",
    example: "SELECT * FROM get_all_pathway_aggregates('place-pktrm');",
    returns: ["from_stops", "to_stops", "modes", "directions", "min_time", "max_time"],
  },
  {
    name: "get_pathways_filtered",
    signature:
      "get_pathways_filtered(station_id, to_stop, from_stop, min_time, max_time, include_null_time, direction_filter, pathway_types)",
    kind: "table",
    category: "pathways",
    description: "Pathways that match optional filters. Pass `NULL` to skip a filter.",
    example:
      "SELECT * FROM get_pathways_filtered('place-pktrm', NULL, NULL, 0, 120, TRUE, NULL, NULL);",
    returns: [
      "pathway_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "from_stop_id",
      "to_stop_id",
      "traversal_time",
      "pathway_mode_name",
      "direction_type",
      "angle",
    ],
  },
  {
    name: "get_direct_pathways",
    signature:
      "get_direct_pathways(p_station_id, from_stop := NULL, to_stop := NULL, direction_filter := NULL, pathway_types := NULL)",
    kind: "table",
    category: "pathways",
    description: "Single-hop pathways with optional filters.",
    example: "SELECT * FROM get_direct_pathways('place-pktrm');",
    returns: [
      "pathway_id",
      "from_stop_id",
      "to_stop_id",
      "from_lat",
      "from_lon",
      "to_lat",
      "to_lon",
      "traversal_time",
      "pathway_mode_name",
      "pathway_mode",
      "direction_type",
      "is_bidirectional",
    ],
  },
  {
    name: "get_from_stops",
    signature: "get_from_stops(station_id, to_stop, min_time, max_time)",
    kind: "table",
    category: "pathways",
    description: "Start stops of pathways that match the filters.",
    example: "SELECT * FROM get_from_stops('place-pktrm', NULL, NULL, NULL);",
    returns: ["from_stop_id"],
  },
  {
    name: "get_to_stops",
    signature: "get_to_stops(station_id, from_stop, min_time, max_time)",
    kind: "table",
    category: "pathways",
    description: "End stops of pathways that match the filters.",
    example: "SELECT * FROM get_to_stops('place-pktrm', NULL, NULL, NULL);",
    returns: ["to_stop_id"],
  },
  {
    name: "get_from_stops_available",
    signature: "get_from_stops_available(station_id)",
    kind: "table",
    category: "pathways",
    description: "Every start stop in a station's pathways.",
    example: "SELECT * FROM get_from_stops_available('place-pktrm');",
    returns: ["from_stop_id"],
  },
  {
    name: "get_to_stops_available",
    signature: "get_to_stops_available(station_id)",
    kind: "table",
    category: "pathways",
    description: "Every end stop in a station's pathways.",
    example: "SELECT * FROM get_to_stops_available('place-pktrm');",
    returns: ["to_stop_id"],
  },
  {
    name: "get_pathway_types",
    signature: "get_pathway_types(station_id, to_stop, from_stop)",
    kind: "table",
    category: "pathways",
    description: "Pathway modes among pathways that match the filters.",
    example: "SELECT * FROM get_pathway_types('place-pktrm', NULL, NULL);",
    returns: ["pathway_mode_name"],
  },
  {
    name: "get_pathway_modes_available",
    signature: "get_pathway_modes_available(station_id)",
    kind: "table",
    category: "pathways",
    description: "Every pathway mode in a station.",
    example: "SELECT * FROM get_pathway_modes_available('place-pktrm');",
    returns: ["pathway_mode_name"],
  },
  {
    name: "get_direction_types",
    signature:
      "get_direction_types(station_id, to_stop, from_stop, min_time, max_time, include_null_time)",
    kind: "table",
    category: "pathways",
    description: "Direction types among pathways that match the filters.",
    example: "SELECT * FROM get_direction_types('place-pktrm', NULL, NULL, NULL, NULL, TRUE);",
    returns: ["direction_type"],
  },
  {
    name: "get_direction_types_available",
    signature: "get_direction_types_available(station_id)",
    kind: "table",
    category: "pathways",
    description: "Every direction type in a station's pathways.",
    example: "SELECT * FROM get_direction_types_available('place-pktrm');",
    returns: ["direction_type"],
  },
  {
    name: "get_time_range",
    signature: "get_time_range(station_id)",
    kind: "table",
    category: "pathways",
    description: "Shortest and longest traversal time in a station.",
    example: "SELECT * FROM get_time_range('place-pktrm');",
    returns: ["min_time", "max_time"],
  },
  {
    name: "get_time_interval_ranges",
    signature: "get_time_interval_ranges(station_id, to_stop, from_stop)",
    kind: "table",
    category: "pathways",
    description: "Logarithmic traversal-time bins for the time slider.",
    example: "SELECT * FROM get_time_interval_ranges('place-pktrm', NULL, NULL);",
    returns: ["min_value", "max_value"],
  },
  {
    name: "find_shortest_path",
    signature: "find_shortest_path(p_station_id, start_stop, end_stop, max_hops := 10)",
    kind: "table",
    category: "pathfinding",
    description:
      "Fastest path between two station parts, with total time, hops and the pathway ids.",
    example:
      "SELECT current_stop, destination, total_time, hop_count\n  FROM find_shortest_path('place-pktrm', 'door-pktrm-elevatorwb', '70075', 10);",
    returns: [
      "current_stop",
      "destination",
      "total_time",
      "hop_count",
      "path_ids",
      "visited_stops",
      "path_description",
    ],
  },
  {
    name: "find_reachable_stops",
    signature: "find_reachable_stops(p_station_id, start_stop, max_time := NULL, max_hops := 5)",
    kind: "table",
    category: "pathfinding",
    description: "Every station part reachable from a start within a time and hop limit.",
    example: "SELECT * FROM find_reachable_stops('place-pktrm', 'door-pktrm-elevatorwb', 120, 3);",
    returns: ["reachable_stop", "min_time", "min_hops"],
  },
  {
    name: "find_all_paths",
    signature: "find_all_paths(p_station_id, start_stop, end_stop, max_hops := 5)",
    kind: "table",
    category: "pathfinding",
    description: "Every path between two station parts up to a hop limit, not only the fastest.",
    example: "SELECT * FROM find_all_paths('place-pktrm', 'door-pktrm-elevatorwb', '70075', 7);",
    returns: ["total_time", "hop_count", "path_ids", "route"],
  },
  {
    name: "get_station_routes",
    signature: "get_station_routes(p_station_id)",
    kind: "table",
    category: "pathfinding",
    description:
      "Shortest time between every reachable pair of station parts. Use it to find platforms that cannot reach an exit.",
    example: "SELECT * FROM get_station_routes('place-pktrm');",
    returns: [
      "start_stop",
      "end_stop",
      "shortest_time",
      "from_location_type_name",
      "to_location_type_name",
    ],
  },
  {
    name: "get_route_info",
    signature: "get_route_info(p_route_id)",
    kind: "table",
    category: "routes",
    description: "One route from `RoutesTable`.",
    example: "SELECT * FROM get_route_info('Red');",
    returns: [
      "row_id",
      "route_id",
      "agency_id",
      "route_short_name",
      "route_long_name",
      "route_name",
      "route_desc",
      "route_type",
      "route_type_name",
      "route_url",
      "route_color",
      "route_text_color",
      "route_color_hex",
      "route_text_color_hex",
      "route_sort_order",
      "stop_count",
      "station_count",
      "shape_count",
      "trip_count",
      "shape_points_json",
      "status",
    ],
  },
  {
    name: "get_route_stops",
    signature: "get_route_stops(p_route_id)",
    kind: "table",
    category: "routes",
    description: "A route's stops in stop-sequence order, with their stations.",
    example: "SELECT * FROM get_route_stops('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "station_id",
      "station_name",
      "stop_sequence",
    ],
  },
  {
    name: "get_route_stations",
    signature: "get_route_stations(p_route_id)",
    kind: "table",
    category: "routes",
    description: "Distinct stations a route serves, with coordinates.",
    example: "SELECT * FROM get_route_stations('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "station_id",
      "station_name",
      "stop_lat",
      "stop_lon",
    ],
  },
  {
    name: "get_route_shapes",
    signature: "get_route_shapes(p_route_id)",
    kind: "table",
    category: "routes",
    description: "Shape points for a route.",
    example: "SELECT * FROM get_route_shapes('Red');",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_lat",
      "shape_pt_lon",
      "shape_pt_sequence",
      "shape_dist_traveled",
    ],
  },
  {
    name: "get_route_stops_for_routes",
    signature: "get_route_stops_for_routes(p_route_ids)",
    kind: "table",
    category: "routes",
    description: "Stops for a list of routes.",
    example: "SELECT * FROM get_route_stops_for_routes(['Red', 'Orange']);",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "stop_id",
      "stop_name",
      "stop_lat",
      "stop_lon",
      "location_type_name",
      "parent_station",
      "station_id",
      "station_name",
      "stop_sequence",
    ],
  },
  {
    name: "get_route_shapes_for_routes",
    signature: "get_route_shapes_for_routes(p_route_ids)",
    kind: "table",
    category: "routes",
    description: "Shape points for a list of routes.",
    example: "SELECT * FROM get_route_shapes_for_routes(['Red', 'Orange']);",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_lat",
      "shape_pt_lon",
      "shape_pt_sequence",
      "shape_dist_traveled",
    ],
  },
  {
    name: "get_stations_map_bounds",
    signature: "get_stations_map_bounds()",
    kind: "table",
    category: "bounds",
    description: "Bounds, centre and zoom for all stations.",
    example: "SELECT * FROM get_stations_map_bounds();",
    returns: ["min_lon", "max_lon", "min_lat", "max_lat", "center_lon", "center_lat", "zoom"],
  },
  {
    name: "get_stops_map_bounds",
    signature: "get_stops_map_bounds()",
    kind: "table",
    category: "bounds",
    description: "Bounds, centre and zoom for all standalone stops.",
    example: "SELECT * FROM get_stops_map_bounds();",
    returns: ["min_lon", "max_lon", "min_lat", "max_lat", "center_lon", "center_lat", "zoom"],
  },
  {
    name: "get_route_map_bounds",
    signature: "get_route_map_bounds(p_route_ids)",
    kind: "table",
    category: "bounds",
    description: "Bounds, centre and zoom for a list of routes, from shapes or stops.",
    example: "SELECT * FROM get_route_map_bounds(['Red']);",
    returns: ["min_lon", "max_lon", "min_lat", "max_lat", "center_lon", "center_lat", "zoom"],
  },
  {
    name: "get_all_shapes_map_bounds",
    signature: "get_all_shapes_map_bounds()",
    kind: "table",
    category: "bounds",
    description: "Bounds, centre and zoom for every shape.",
    example: "SELECT * FROM get_all_shapes_map_bounds();",
    returns: ["min_lon", "max_lon", "min_lat", "max_lat", "center_lon", "center_lat", "zoom"],
  },
  {
    name: "get_trip_map_bounds",
    signature: "get_trip_map_bounds(p_trip_id)",
    kind: "table",
    category: "bounds",
    description: "Bounds, centre and zoom for one trip's stops.",
    example: "SELECT * FROM get_trip_map_bounds('canonical-Red-C1-0');",
    returns: ["min_lon", "max_lon", "min_lat", "max_lat", "center_lon", "center_lat", "zoom"],
  },
  {
    name: "get_route_corridors",
    signature: "get_route_corridors(p_route_ids, snap_precision := 4)",
    kind: "table",
    category: "bands",
    description: "Shape segments that two or more of the given routes share.",
    example: "SELECT * FROM get_route_corridors(['Green-B', 'Green-C', 'Green-D', 'Green-E']);",
    returns: ["corridor_key", "route_id", "band_index", "band_count"],
  },
  {
    name: "prepare_route_shape_lanes",
    signature:
      "prepare_route_shape_lanes(p_route_ids, spacing_meters := 16.0, snap_precision := 4, simplify_meters := 0.5, reach_meters := 18.0, p_kind := 'route')",
    kind: "table",
    category: "bands",
    description:
      "Phase one: assign each route a lane in every corridor it shares. Pass trip ids with `p_kind := 'trip'`.",
    example:
      "SELECT * FROM prepare_route_shape_lanes(['Green-B', 'Green-C', 'Green-D', 'Green-E']);",
    returns: [
      "route_id",
      "shape_id",
      "shape_pt_sequence",
      "lat",
      "lon",
      "coslat",
      "ux",
      "uy",
      "band_index",
      "band_count",
      "shift_s",
      "slot_s",
      "plat",
      "plon",
      "nlat",
      "nlon",
    ],
  },
  {
    name: "prepare_route_shape_lanes_rail",
    signature: "prepare_route_shape_lanes_rail()",
    kind: "table",
    category: "bands",
    description: "Phase one for every rail route, with rail spacing.",
    example: "SELECT * FROM prepare_route_shape_lanes_rail();",
    returns: [
      "route_id",
      "shape_id",
      "shape_pt_sequence",
      "lat",
      "lon",
      "coslat",
      "ux",
      "uy",
      "band_index",
      "band_count",
      "shift_s",
      "slot_s",
      "plat",
      "plon",
      "nlat",
      "nlon",
    ],
  },
  {
    name: "prepare_route_shape_lanes_bus",
    signature: "prepare_route_shape_lanes_bus()",
    kind: "table",
    category: "bands",
    description: "Phase one for every bus and trolleybus route, with bus spacing.",
    example: "SELECT * FROM prepare_route_shape_lanes_bus();",
    returns: [
      "route_id",
      "shape_id",
      "shape_pt_sequence",
      "lat",
      "lon",
      "coslat",
      "ux",
      "uy",
      "band_index",
      "band_count",
      "shift_s",
      "slot_s",
      "plat",
      "plon",
      "nlat",
      "nlon",
    ],
  },
  {
    name: "prepare_route_shape_lanes_other",
    signature: "prepare_route_shape_lanes_other()",
    kind: "table",
    category: "bands",
    description: "Phase one for routes that are neither rail nor bus, such as ferries.",
    example: "SELECT * FROM prepare_route_shape_lanes_other();",
    returns: [
      "route_id",
      "shape_id",
      "shape_pt_sequence",
      "lat",
      "lon",
      "coslat",
      "ux",
      "uy",
      "band_index",
      "band_count",
      "shift_s",
      "slot_s",
      "plat",
      "plon",
      "nlat",
      "nlon",
    ],
  },
  {
    name: "finish_route_shape_bands",
    signature: "finish_route_shape_bands(p_route_ids)",
    kind: "table",
    category: "bands",
    description:
      "Phase two: smooth the staged lanes in `RouteShapeLanesTable` for the given routes into band rows.",
    example:
      "INSERT INTO RouteShapeLanesTable\n  SELECT * FROM prepare_route_shape_lanes(['Green-B', 'Green-C']);\nSELECT * FROM finish_route_shape_bands(['Green-B', 'Green-C']);",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_sequence",
      "shape_pt_lat",
      "shape_pt_lon",
      "band_index",
      "band_count",
      "slot",
      "turn_radius",
    ],
    note: "Needs a writable database.",
  },
  {
    name: "refresh_route_shape_bands",
    signature: "refresh_route_shape_bands()",
    kind: "table",
    category: "bands",
    description: "Phase two for every route staged in `RouteShapeLanesTable`.",
    example:
      "INSERT INTO RouteShapeLanesTable SELECT * FROM prepare_route_shape_lanes_rail();\nINSERT INTO RouteShapeBandsTable SELECT * FROM refresh_route_shape_bands();",
    returns: [
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "shape_id",
      "shape_pt_sequence",
      "shape_pt_lat",
      "shape_pt_lon",
      "band_index",
      "band_count",
      "slot",
      "turn_radius",
    ],
    note: "Needs a writable database. `gtfs-viz route-bands` runs this pipeline.",
  },
  {
    name: "get_station_line_bands",
    signature: "get_station_line_bands(p_ids, p_kind := 'route', spacing_meters := 30.0)",
    kind: "table",
    category: "bands",
    description:
      "Schematic straight lines between the stations each route (or trip, with `p_kind := 'trip'`) visits, fanned into parallel bands where they share a corridor.",
    example: "SELECT * FROM get_station_line_bands(['Red', 'Orange']);",
    returns: [
      "entity_kind",
      "entity_id",
      "route_id",
      "route_name",
      "route_color_hex",
      "route_text_color_hex",
      "route_type_name",
      "shape_id",
      "shape_pt_lat",
      "shape_pt_lon",
      "shape_pt_sequence",
      "shape_dist_traveled",
      "band_index",
      "band_count",
    ],
  },
  {
    name: "get_trip_stops",
    signature: "get_trip_stops(p_trip_id, p_remove_names, p_first_name, p_last_name)",
    kind: "table",
    category: "trips",
    description:
      "A trip's stops with times, optionally dropping named stops or cutting it to a first and last stop.",
    example: "SELECT * FROM get_trip_stops('canonical-Red-C1-0', [], NULL, NULL);",
    returns: ["stop_sequence", "stop_id", "arrival_time", "departure_time"],
  },
  {
    name: "get_trip_reroute_routes",
    signature: "get_trip_reroute_routes(p_trip_id)",
    kind: "table",
    category: "trips",
    description:
      "Routes with a donor trip whose stops differ from the trip between at least two shared stations.",
    example: "SELECT * FROM get_trip_reroute_routes('canonical-Green-B-C1-0');",
    returns: [
      "route_id",
      "route_name",
      "route_short_name",
      "route_type_name",
      "route_color_hex",
      "donor_trip_id",
      "shared_station_count",
    ],
  },
  {
    name: "get_trip_reroute_boundary_pairs",
    signature: "get_trip_reroute_boundary_pairs(p_trip_id, p_donor_trip_id)",
    kind: "table",
    category: "trips",
    description:
      "Shared station pairs between which the trip and the donor stop at different places.",
    example:
      "SELECT * FROM get_trip_reroute_boundary_pairs('canonical-Green-B-C1-0', 'canonical-Green-D-C1-0');",
    returns: [
      "from_station",
      "to_station",
      "affected_from_sequence",
      "affected_to_sequence",
      "donor_from_sequence",
      "donor_to_sequence",
    ],
  },
  {
    name: "get_reroute_stop_times",
    signature: "get_reroute_stop_times(p_trip_id, p_donor_trip_id, p_from_name, p_to_name)",
    kind: "table",
    category: "trips",
    description:
      "The trip with the section between two stations replaced by the donor's stops, timing scaled into the trip's window.",
    example:
      "SELECT * FROM get_reroute_stop_times('canonical-Green-B-C1-0', 'canonical-Green-D-C1-0', 'Government Center', 'Copley');",
    returns: ["stop_sequence", "stop_id", "arrival_time", "departure_time"],
  },
]
