-- ============================================================================
-- GTFS Extension for DuckDB
-- ============================================================================
-- Auto-generated by scripts/bundle-sql.mjs — do not edit
-- Load with:  .read gtfs.sql
-- ============================================================================

-- utils/gtfs_enums
CREATE OR REPLACE MACRO pathway_mode_to_name(mode) AS (
  CASE mode
    WHEN 1 THEN 'Walkway'
    WHEN 2 THEN 'Stairs'
    WHEN 3 THEN 'Moving sidewalk/travelator'
    WHEN 4 THEN 'Escalator'
    WHEN 5 THEN 'Elevator'
    WHEN 6 THEN 'Fare gate'
    WHEN 7 THEN 'Exit gate'
    ELSE '❓'
  END
);

CREATE OR REPLACE MACRO bidirectional_to_direction(is_bidirectional) AS (
  CASE is_bidirectional
    WHEN 0 THEN 'directional'
    WHEN 1 THEN 'bidirectional'
    ELSE 'unknown'
  END
);

CREATE OR REPLACE MACRO location_type_to_name(location_type, parent_station) AS (
  CASE
    WHEN location_type = 0 AND COALESCE(parent_station, '') != '' THEN 'Platform'
    WHEN location_type = 0 THEN 'Stop'
    WHEN location_type = 1 THEN 'Station'
    WHEN location_type = 2 THEN 'Exit/Entrance'
    WHEN location_type = 3 THEN 'Pathway Node'
    WHEN location_type = 4 THEN 'Boarding Area'
    ELSE 'Unknown'
  END
);

CREATE OR REPLACE MACRO wheelchair_to_emoji(wheelchair_boarding) AS (
  CASE wheelchair_boarding
    WHEN 0 THEN '🔵'
    WHEN 1 THEN '🟢'
    WHEN 2 THEN '🔴'
    ELSE '🟡'
  END
);

-- tables/create_edit_stop_table
CREATE TABLE IF NOT EXISTS EditStopTable (
    row_id TEXT NOT NULL,
    stop_id TEXT NOT NULL,
    stop_name TEXT,
    stop_lat DOUBLE PRECISION,
    stop_lon DOUBLE PRECISION,
    location_type_name TEXT,
    parent_station TEXT,
    level_id TEXT,
    wheelchair_status TEXT,
    status TEXT
);

ALTER TABLE EditStopTable ADD COLUMN IF NOT EXISTS level_id TEXT;

-- tables/create_edit_pathway_table
CREATE TABLE IF NOT EXISTS EditPathwayTable (
    row_id INTEGER NOT NULL,
    pathway_id TEXT NOT NULL,
    from_stop_id TEXT NOT NULL,
    to_stop_id TEXT NOT NULL,
    pathway_mode INTEGER DEFAULT 1,
    is_bidirectional INTEGER DEFAULT 1,
    length DOUBLE,
    traversal_time INTEGER,
    stair_count INTEGER,
    max_slope DOUBLE,
    min_width DOUBLE,
    signposted_as TEXT,
    reversed_signposted_as TEXT,
    status TEXT
);

-- tables/create_stops_view
CREATE OR REPLACE VIEW StopsView AS
SELECT
  row_id,
  stop_id,
  stop_name,
  stop_lat,
  stop_lon,
  location_type_name,
  parent_station,
  level_id,
  wheelchair_status,
  status
FROM (
  SELECT
    edt.row_id,
    edt.stop_id,
    edt.stop_name,
    edt.stop_lat,
    edt.stop_lon,
    edt.location_type_name,
    edt.parent_station,
    edt.level_id,
    edt.wheelchair_status,
    edt.status
  FROM EditStopTable edt
  WHERE edt.status IN ('new', 'edit', 'new edit')
  UNION ALL
  SELECT
    st.row_id,
    st.stop_id,
    st.stop_name,
    st.stop_lat,
    st.stop_lon,
    st.location_type_name,
    st.parent_station,
    st.level_id,
    st.wheelchair_status,
    '' AS status
  FROM stops st
  WHERE NOT EXISTS (
    SELECT 1
    FROM EditStopTable edt
    WHERE edt.row_id = st.row_id
      AND edt.status = 'deleted'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM EditStopTable edt
    WHERE edt.row_id = st.row_id
      AND edt.status = 'edit'
  )
) combined;

-- tables/create_pathways_view
CREATE OR REPLACE VIEW PathwaysView AS
SELECT
  row_id,
  pathway_id,
  from_stop_id,
  to_stop_id,
  pathway_mode,
  is_bidirectional,
  length,
  traversal_time,
  stair_count,
  max_slope,
  min_width,
  signposted_as,
  reversed_signposted_as,
  pathway_mode_name,
  direction_type,
  status
FROM (
  -- Edited or new pathways from EditPathwayTable
  SELECT
    edt.row_id,
    edt.pathway_id,
    edt.from_stop_id,
    edt.to_stop_id,
    edt.pathway_mode,
    edt.is_bidirectional,
    edt.length,
    edt.traversal_time,
    edt.stair_count,
    edt.max_slope,
    edt.min_width,
    edt.signposted_as,
    edt.reversed_signposted_as,
    pathway_mode_to_name(edt.pathway_mode) AS pathway_mode_name,
    bidirectional_to_direction(edt.is_bidirectional) AS direction_type,
    edt.status
  FROM EditPathwayTable edt
  WHERE edt.status IN ('new', 'edit', 'new edit')

  UNION ALL

  -- Original pathways from pathways table
  SELECT
    pt.row_id,
    pt.pathway_id,
    pt.from_stop_id,
    pt.to_stop_id,
    pt.pathway_mode,
    pt.is_bidirectional,
    pt.length,
    pt.traversal_time,
    pt.stair_count,
    pt.max_slope,
    pt.min_width,
    pt.signposted_as,
    pt.reversed_signposted_as,
    pt.pathway_mode_name,
    pt.direction_type,
    '' AS status
  FROM pathways pt
  WHERE NOT EXISTS (
    SELECT 1
    FROM EditPathwayTable edt
    WHERE edt.row_id = pt.row_id
      AND edt.status = 'deleted'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM EditPathwayTable edt
    WHERE edt.row_id = pt.row_id
      AND edt.status = 'edit'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM EditPathwayTable edt
    WHERE edt.pathway_id = pt.pathway_id
      AND edt.status = 'new edit'
  )
) combined;

-- tables/create_station_views
CREATE OR REPLACE MACRO get_stops_view_data() AS TABLE (
  SELECT
    row_id,
    stop_id,
    stop_name,
    stop_lat,
    stop_lon,
    location_type_name,
    parent_station,
    level_id,
    wheelchair_status,
    status
  FROM (
    SELECT
      edt.row_id,
      edt.stop_id,
      edt.stop_name,
      edt.stop_lat,
      edt.stop_lon,
      edt.location_type_name,
      edt.parent_station,
      edt.level_id,
      edt.wheelchair_status,
      edt.status
    FROM EditStopTable edt
    WHERE edt.status IN ('new', 'edit', 'new edit')
    UNION ALL
    SELECT
      st.row_id,
      st.stop_id,
      st.stop_name,
      st.stop_lat,
      st.stop_lon,
      st.location_type_name,
      st.parent_station,
      st.level_id,
      st.wheelchair_status,
      '' AS status
    FROM stops st
    WHERE NOT EXISTS (
      SELECT 1
      FROM EditStopTable edt
      WHERE edt.row_id = st.row_id
        AND edt.status = 'deleted'
    )
    AND NOT EXISTS (
      SELECT 1
      FROM EditStopTable edt
      WHERE edt.row_id = st.row_id
        AND edt.status = 'edit'
    )
  ) combined
);

CREATE OR REPLACE MACRO get_stops_table_data() AS TABLE (
  SELECT
    s.row_id,
    s.stop_id,
    s.stop_name,
    s.stop_lat,
    s.stop_lon,
    s.status,
    s.location_type_name,
    s.parent_station,
    s.level_id,
    s.wheelchair_status
  FROM StopsView s
  WHERE s.location_type_name != 'Station'
    AND (s.parent_station IS NULL OR s.parent_station = '')
);

CREATE OR REPLACE MACRO get_stations_table_data() AS TABLE (
  WITH exit_counts AS (
    SELECT
      parent_station,
      COUNT(*) AS exit_count
    FROM StopsView
    WHERE location_type_name = 'Exit/Entrance'
    GROUP BY parent_station
  ),
  all_pathways AS (
    SELECT
      s.stop_id AS station_id,
      p.pathway_id
    FROM StopsView s
    LEFT JOIN stops st
      ON st.parent_station = s.stop_id
    LEFT JOIN PathwaysView p
      ON p.from_stop_id IN (s.stop_id, st.stop_id)
      OR p.to_stop_id IN (s.stop_id, st.stop_id)
  ),
  pathway_counts AS (
    SELECT
      station_id,
      COUNT(DISTINCT pathway_id) AS pathway_count
    FROM all_pathways
    GROUP BY station_id
  )
  SELECT
    s.row_id,
    s.stop_id,
    s.stop_name,
    s.stop_lat,
    s.stop_lon,
    s.status,
    COALESCE(e.exit_count, 0) AS exit_count,
    s.location_type_name,
    s.parent_station,
    s.wheelchair_status,
    CASE
      WHEN COALESCE(pc.pathway_count, 0) = 0 THEN '❌'
      WHEN COALESCE(pc.pathway_count, 0) > 0 THEN '✅'
      WHEN COALESCE(pc.pathway_count, 0) = 0
           AND COALESCE(e.exit_count, 0) > 0
      THEN '🟡'
      ELSE '❌'
    END AS pathways_status
  FROM StopsView s
  LEFT JOIN exit_counts e
    ON e.parent_station = s.stop_id
  LEFT JOIN pathway_counts pc
    ON pc.station_id = s.stop_id
  WHERE s.location_type_name = 'Station'
);

-- tables/create_stops_table
CREATE OR REPLACE TABLE StopsTable AS SELECT * FROM get_stops_table_data();

-- tables/create_stations_table
CREATE OR REPLACE TABLE StationsTable AS SELECT * FROM get_stations_table_data();

-- tables/initialize_pathway_network
CREATE OR REPLACE VIEW pathway_network AS
SELECT
  p.row_id,
  p.pathway_id,
  p.from_stop_id,
  p.to_stop_id,
  p.pathway_mode,
  p.is_bidirectional,
  p.length,
  p.traversal_time,
  p.stair_count,
  p.max_slope,
  p.min_width,
  p.signposted_as,
  p.reversed_signposted_as,
  p.pathway_mode_name,
  p.direction_type,

  COALESCE(NULLIF(s1.parent_station, ''), s1.stop_id) AS from_parent_station,
  s1.stop_lat AS from_lat,
  s1.stop_lon AS from_lon,
  s1.location_type_name AS from_location_type_name,

  COALESCE(NULLIF(s2.parent_station, ''), s2.stop_id) AS to_parent_station,
  s2.stop_lat AS to_lat,
  s2.stop_lon AS to_lon,
  s2.location_type_name AS to_location_type_name,

  CASE
    WHEN s1.stop_lat IS NOT NULL AND s1.stop_lon IS NOT NULL
         AND s2.stop_lat IS NOT NULL AND s2.stop_lon IS NOT NULL
    THEN DEGREES(
      ATAN2(
        s2.stop_lon - s1.stop_lon,
        s2.stop_lat - s1.stop_lat
      )
    )
    ELSE NULL
  END AS angle
FROM PathwaysView p
JOIN StopsView s1 ON p.from_stop_id = s1.stop_id
JOIN StopsView s2 ON p.to_stop_id = s2.stop_id;

CREATE INDEX IF NOT EXISTS idx_pathways_from_stop ON pathways(from_stop_id);
CREATE INDEX IF NOT EXISTS idx_pathways_to_stop ON pathways(to_stop_id);
CREATE INDEX IF NOT EXISTS idx_pathways_bidirectional ON pathways(is_bidirectional);
CREATE INDEX IF NOT EXISTS idx_stops_parent_station ON stops(parent_station);
CREATE INDEX IF NOT EXISTS idx_stops_location_type ON stops(location_type);

-- queries/get_station_info
CREATE OR REPLACE MACRO get_station_info(station_id) AS TABLE (
  WITH station_base AS (
    SELECT
      row_id,
      stop_id,
      stop_name,
      stop_lat,
      stop_lon,
      '🔵' AS status,
      location_type_name,
      parent_station,
      wheelchair_status
    FROM StopsView
    WHERE location_type_name = 'Station'
      AND stop_id = station_id
  ),
  exit_counts AS (
    SELECT
      COUNT(*) AS exit_count
    FROM StopsView
    WHERE location_type_name = 'Exit/Entrance'
      AND parent_station = station_id
  ),
  pathway_counts AS (
    SELECT
      COUNT(DISTINCT p.pathway_id) AS pathway_count
    FROM PathwaysView p
    JOIN StopsView s1 ON p.from_stop_id = s1.stop_id
    JOIN StopsView s2 ON p.to_stop_id = s2.stop_id
    WHERE (
      COALESCE(NULLIF(s1.parent_station, ''), s1.stop_id) = station_id
      AND COALESCE(NULLIF(s2.parent_station, ''), s2.stop_id) = station_id
    )
  )
  SELECT
    s.row_id,
    s.stop_id,
    s.stop_name,
    s.stop_lat,
    s.stop_lon,
    s.status,
    COALESCE(e.exit_count, 0) AS exit_count,
    s.location_type_name,
    s.parent_station,
    s.wheelchair_status,
    COALESCE(pc.pathway_count, 0) AS pathway_count,
    CASE
      WHEN COALESCE(pc.pathway_count, 0) = 0 THEN '❌'
      WHEN COALESCE(pc.pathway_count, 0) > 0 THEN '✅'
      WHEN COALESCE(pc.pathway_count, 0) = 0
        AND COALESCE(e.exit_count, 0) > 0
      THEN '🟡'
      ELSE '❌'
    END AS pathways_status
  FROM station_base s
  CROSS JOIN exit_counts e
  CROSS JOIN pathway_counts pc
);

-- queries/get_station_stops
CREATE OR REPLACE MACRO get_station_stops(station_id) AS TABLE (
  WITH station_stops AS (
    SELECT
      s.row_id,
      s.stop_id,
      s.stop_name,
      s.stop_lat,
      s.stop_lon,
      s.location_type_name,
      s.parent_station,
      s.level_id,
      s.wheelchair_status,
      s.status
    FROM StopsView s

    UNION ALL

    SELECT
      edt.row_id,
      edt.stop_id,
      edt.stop_name,
      edt.stop_lat,
      edt.stop_lon,
      edt.location_type_name,
      edt.parent_station,
      edt.level_id,
      edt.wheelchair_status,
      edt.status
    FROM EditStopTable edt
    WHERE edt.status = 'deleted'
      AND NOT EXISTS (
        SELECT 1
        FROM StopsView s
        WHERE s.stop_id = edt.stop_id
      )
  )
  SELECT DISTINCT
    s.row_id,
    s.stop_id,
    s.stop_name,
    s.stop_lat,
    s.stop_lon,
    s.location_type_name,
    s.parent_station,
    s.level_id,
    s.wheelchair_status,
    s.status
  FROM station_stops s
  WHERE COALESCE(NULLIF(s.parent_station, ''), s.stop_id) = station_id
  ORDER BY s.stop_id
);

-- queries/get_station_pathways
CREATE OR REPLACE MACRO get_station_pathways(station_id) AS TABLE (
  WITH stop_lookup AS (
    SELECT
      s.stop_id,
      s.stop_name,
      s.stop_lat,
      s.stop_lon,
      s.location_type_name,
      s.parent_station,
      s.status
    FROM StopsView s

    UNION ALL

    SELECT
      edt.stop_id,
      edt.stop_name,
      edt.stop_lat,
      edt.stop_lon,
      edt.location_type_name,
      edt.parent_station,
      edt.status
    FROM EditStopTable edt
    WHERE edt.status = 'deleted'
      AND NOT EXISTS (
        SELECT 1
        FROM StopsView s
        WHERE s.stop_id = edt.stop_id
      )
  )
  SELECT
    p.row_id,
    p.pathway_id,
    p.from_stop_id,
    p.to_stop_id,
    s1.stop_lat as from_lat,
    s1.stop_lon as from_lon,
    s2.stop_lat as to_lat,
    s2.stop_lon as to_lon,
    p.traversal_time,
    p.length,
    p.stair_count,
    p.max_slope,
    p.min_width,
    p.signposted_as,
    p.reversed_signposted_as,
    COALESCE(p.pathway_mode_name, pathway_mode_to_name(p.pathway_mode)) as pathway_mode_name,
    p.pathway_mode,
    COALESCE(p.direction_type, bidirectional_to_direction(p.is_bidirectional)) as direction_type,
    p.is_bidirectional,
    p.status,
    s1.location_type_name AS from_location_type_name,
    s2.location_type_name AS to_location_type_name,
    COALESCE(NULLIF(s1.parent_station, ''), s1.stop_id) AS from_parent_station,
    COALESCE(NULLIF(s2.parent_station, ''), s2.stop_id) AS to_parent_station,
    CASE
      WHEN s1.stop_lat IS NOT NULL AND s1.stop_lon IS NOT NULL
           AND s2.stop_lat IS NOT NULL AND s2.stop_lon IS NOT NULL
      THEN DEGREES(
        ATAN2(
          s2.stop_lon - s1.stop_lon,
          s2.stop_lat - s1.stop_lat
        )
      )
      ELSE NULL
    END as angle
  FROM PathwaysView p
  LEFT JOIN stop_lookup s1 ON p.from_stop_id = s1.stop_id
  LEFT JOIN stop_lookup s2 ON p.to_stop_id = s2.stop_id
  WHERE COALESCE(NULLIF(s1.parent_station, ''), s1.stop_id) = station_id
     OR COALESCE(NULLIF(s2.parent_station, ''), s2.stop_id) = station_id
  ORDER BY p.pathway_id
);

-- queries/get_pathway_aggregates
CREATE OR REPLACE MACRO get_from_stops_available(station_id) AS TABLE (
  SELECT DISTINCT from_stop_id
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
  ORDER BY from_stop_id
);

CREATE OR REPLACE MACRO get_to_stops_available(station_id) AS TABLE (
  SELECT DISTINCT to_stop_id
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
  ORDER BY to_stop_id
);

CREATE OR REPLACE MACRO get_station_connections(station_id) AS TABLE (
  WITH directed_connections AS (
    SELECT
      pathway_id,
      from_stop_id,
      to_stop_id,
      traversal_time,
      length,
      pathway_mode_name,
      direction_type,
      is_bidirectional,
      angle,
      'forward' AS edge_direction
    FROM pathway_network
    WHERE from_parent_station = station_id
      AND to_parent_station = station_id
      AND to_stop_id != from_stop_id

    UNION ALL

    SELECT
      pathway_id,
      to_stop_id AS from_stop_id,
      from_stop_id AS to_stop_id,
      traversal_time,
      length,
      pathway_mode_name,
      direction_type,
      is_bidirectional,
      angle,
      'reverse' AS edge_direction
    FROM pathway_network
    WHERE from_parent_station = station_id
      AND to_parent_station = station_id
      AND is_bidirectional = 1
      AND to_stop_id != from_stop_id
  )
  SELECT
    dc.pathway_id,
    dc.from_stop_id,
    from_stop.stop_name AS from_stop_name,
    from_stop.location_type_name AS from_location_type_name,
    dc.to_stop_id,
    to_stop.stop_name AS to_stop_name,
    to_stop.location_type_name AS to_location_type_name,
    dc.traversal_time AS traversal_time_seconds,
    CASE
      WHEN dc.traversal_time IS NULL THEN 'unknown'
      ELSE CAST(dc.traversal_time AS VARCHAR) || ' seconds'
    END AS time_period,
    dc.length,
    dc.pathway_mode_name,
    dc.direction_type,
    dc.is_bidirectional,
    dc.edge_direction,
    dc.angle
  FROM directed_connections dc
  LEFT JOIN StopsView from_stop
    ON from_stop.stop_id = dc.from_stop_id
  LEFT JOIN StopsView to_stop
    ON to_stop.stop_id = dc.to_stop_id
  ORDER BY dc.from_stop_id, dc.to_stop_id, dc.pathway_id, dc.edge_direction
);

CREATE OR REPLACE MACRO get_pathway_modes_available(station_id) AS TABLE (
  SELECT DISTINCT pathway_mode_name
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
  ORDER BY pathway_mode_name
);

CREATE OR REPLACE MACRO get_direction_types_available(station_id) AS TABLE (
  SELECT DISTINCT direction_type
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
  ORDER BY direction_type
);

CREATE OR REPLACE MACRO get_time_range(station_id) AS TABLE (
  SELECT
    MIN(traversal_time) AS min_time,
    MAX(traversal_time) AS max_time
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
    AND traversal_time IS NOT NULL
);

CREATE OR REPLACE MACRO get_all_pathway_aggregates(station_id) AS TABLE (
  WITH aggregates AS (
    SELECT
      LIST(DISTINCT from_stop_id ORDER BY from_stop_id) AS from_stops,
      LIST(DISTINCT to_stop_id ORDER BY to_stop_id) AS to_stops,
      LIST(DISTINCT pathway_mode_name ORDER BY pathway_mode_name) AS modes,
      LIST(DISTINCT direction_type ORDER BY direction_type) AS directions,
      MIN(traversal_time) AS min_time,
      MAX(traversal_time) AS max_time
    FROM pathway_network
    WHERE from_parent_station = station_id
      AND to_parent_station = station_id
  )
  SELECT * FROM aggregates
);

-- queries/get_pathways_filtered
CREATE OR REPLACE MACRO get_pathways_filtered(
  station_id,
  to_stop,
  from_stop,
  min_time,
  max_time,
  include_null_time,
  direction_filter,
  pathway_types
) AS TABLE (
  SELECT
    pathway_id,
    from_lat,
    from_lon,
    to_lat,
    to_lon,
    from_stop_id,
    to_stop_id,
    traversal_time,
    pathway_mode_name,
    direction_type,
    angle
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
    AND (to_stop IS NULL OR to_stop_id = to_stop)
    AND (from_stop IS NULL OR from_stop_id = from_stop)
    AND (
      min_time IS NULL
      OR (
        (traversal_time >= min_time AND traversal_time <= max_time)
        OR (include_null_time = FALSE AND traversal_time IS NULL)
      )
    )
    AND (direction_filter IS NULL OR direction_type = direction_filter)
    AND (pathway_types IS NULL OR pathway_mode_name IN (SELECT unnest(pathway_types)))
);

CREATE OR REPLACE MACRO get_station_stops_for_pathways(station_id) AS TABLE (
  SELECT *
  FROM stops
  WHERE parent_station = station_id
);

CREATE OR REPLACE MACRO get_to_stops(station_id, from_stop, min_time, max_time) AS TABLE (
  SELECT DISTINCT to_stop_id
  FROM pathway_network
  WHERE to_parent_station = station_id
    AND from_parent_station = station_id
    AND to_stop_id != from_stop_id
    AND (from_stop IS NULL OR from_stop_id = from_stop)
    AND (min_time IS NULL OR (traversal_time >= min_time AND traversal_time <= max_time))
);

CREATE OR REPLACE MACRO get_from_stops(station_id, to_stop, min_time, max_time) AS TABLE (
  SELECT DISTINCT from_stop_id
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
    AND to_stop_id != from_stop_id
    AND (to_stop IS NULL OR to_stop_id = to_stop)
    AND (min_time IS NULL OR (traversal_time >= min_time AND traversal_time <= max_time))
);

CREATE OR REPLACE MACRO get_direction_types(
  station_id,
  to_stop,
  from_stop,
  min_time,
  max_time,
  include_null_time
) AS TABLE (
  SELECT DISTINCT direction_type
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
    AND to_stop_id != from_stop_id
    AND (to_stop IS NULL OR to_stop_id = to_stop)
    AND (from_stop IS NULL OR from_stop_id = from_stop)
    AND (
      min_time IS NULL
      OR (
        (traversal_time >= min_time AND traversal_time <= max_time)
        OR (include_null_time = FALSE AND traversal_time IS NULL)
      )
    )
);

CREATE OR REPLACE MACRO get_pathway_types(station_id, to_stop, from_stop) AS TABLE (
  SELECT DISTINCT pathway_mode_name
  FROM pathway_network
  WHERE from_parent_station = station_id
    AND to_parent_station = station_id
    AND to_stop_id != from_stop_id
    AND (to_stop IS NULL OR to_stop_id = to_stop)
    AND (from_stop IS NULL OR from_stop_id = from_stop)
);

-- queries/get_time_interval_ranges
CREATE OR REPLACE MACRO get_time_interval_ranges(station_id, to_stop, from_stop) AS TABLE (
  WITH valid_traversals AS (
    SELECT traversal_time
    FROM pathway_network
    WHERE from_parent_station = station_id
      AND to_parent_station = station_id
      AND (to_stop IS NULL OR to_stop_id = to_stop)
      AND (from_stop IS NULL OR from_stop_id = from_stop)
      AND traversal_time IS NOT NULL
      AND traversal_time > 0
  ),
  time_stats AS (
    SELECT
      MIN(traversal_time) AS min_time,
      MAX(traversal_time) AS max_time
    FROM valid_traversals
  ),
  bins AS (
    SELECT
      ts.min_time,
      ts.max_time,
      LN(ts.min_time) AS log_min_time,
      LN(ts.max_time) AS log_max_time,
      CASE
        WHEN LN(ts.max_time) = LN(ts.min_time) THEN NULL
        ELSE (LN(ts.max_time) - LN(ts.min_time)) / 5.0
      END AS interval_size
    FROM time_stats ts
  ),
  ranges AS (
    SELECT
      b.log_min_time + b.interval_size * generate_series AS range_start_log,
      b.log_min_time + b.interval_size * (generate_series + 1) AS range_end_log
    FROM bins b,
    generate_series(0, 4)
    WHERE b.interval_size IS NOT NULL
  ),
  final_ranges AS (
    SELECT
      EXP(r.range_start_log) AS min_value,
      EXP(r.range_end_log) AS max_value
    FROM ranges r
  )
  SELECT DISTINCT
    CASE
      WHEN min_value % 1 = 0 THEN CAST(min_value AS INT)
      ELSE ROUND(min_value, 2)
    END AS min_value,
    CASE
      WHEN max_value % 1 = 0 THEN CAST(max_value AS INT)
      ELSE ROUND(max_value, 2)
    END AS max_value
  FROM final_ranges
  ORDER BY min_value
);

-- queries/get_station_routes
-- Get station routes (shortest paths between all node pairs within a station)
CREATE OR REPLACE MACRO get_station_routes(station_id) AS TABLE (
  WITH RECURSIVE shortest_paths AS (
    SELECT
      p.from_stop_id AS start_stop,
      p.to_stop_id AS end_stop,
      p.traversal_time AS total_time,
      1 AS hop_count,
      ARRAY[p.from_stop_id] AS path_stops
    FROM pathway_network p
    WHERE p.from_parent_station = station_id
      AND p.to_parent_station = station_id
      AND p.from_stop_id != p.to_stop_id
      AND p.traversal_time IS NOT NULL

    UNION

    SELECT
      sp.start_stop,
      p.to_stop_id AS end_stop,
      sp.total_time + p.traversal_time AS total_time,
      sp.hop_count + 1 AS hop_count,
      array_append(sp.path_stops, p.to_stop_id) AS path_stops
    FROM shortest_paths sp
    JOIN pathway_network p
      ON sp.end_stop = p.from_stop_id
      AND p.from_parent_station = station_id
      AND p.to_parent_station = station_id
      AND p.traversal_time IS NOT NULL
    WHERE sp.hop_count < 8
      AND p.to_stop_id != sp.start_stop
      AND NOT list_contains(sp.path_stops, p.to_stop_id)
      AND NOT EXISTS (
        SELECT 1 FROM shortest_paths sp2
        WHERE sp2.start_stop = sp.start_stop
          AND sp2.end_stop = p.to_stop_id
          AND sp2.total_time <= sp.total_time + p.traversal_time
      )
  ),
  min_paths AS (
    SELECT
      start_stop,
      end_stop,
      MIN(total_time) AS shortest_time
    FROM shortest_paths
    GROUP BY start_stop, end_stop
  ),
  null_connections AS (
    SELECT DISTINCT
      p.from_stop_id AS start_stop,
      p.to_stop_id AS end_stop,
      NULL::DOUBLE AS shortest_time
    FROM pathway_network p
    WHERE p.from_parent_station = station_id
      AND p.to_parent_station = station_id
      AND p.from_stop_id != p.to_stop_id
      AND p.traversal_time IS NULL
  ),
  all_routes AS (
    SELECT * FROM min_paths
    UNION ALL
    SELECT * FROM null_connections
    WHERE NOT EXISTS (
      SELECT 1 FROM min_paths mp
      WHERE mp.start_stop = null_connections.start_stop
        AND mp.end_stop = null_connections.end_stop
    )
  )
  SELECT
    ar.start_stop,
    ar.end_stop,
    ar.shortest_time,
    s1.location_type_name AS from_location_type_name,
    s2.location_type_name AS to_location_type_name
  FROM all_routes ar
  LEFT JOIN stops s1 ON s1.stop_id = ar.start_stop
  LEFT JOIN stops s2 ON s2.stop_id = ar.end_stop
  ORDER BY ar.start_stop, ar.end_stop
);

-- pathfinding/find_shortest_path
CREATE OR REPLACE MACRO find_shortest_path(
  p_station_id VARCHAR,
  start_stop VARCHAR,
  end_stop VARCHAR,
  max_hops INTEGER := 10
) AS TABLE (
  WITH RECURSIVE path_search AS (
    SELECT
      from_stop_id AS current_stop,
      to_stop_id AS next_stop,
      pathway_id,
      pathway_mode_name,
      COALESCE(traversal_time, 0) AS segment_time,
      COALESCE(traversal_time, 0) AS total_time,
      1 AS hop_count,
      ARRAY[from_stop_id] AS visited_stops,
      ARRAY[pathway_id] AS path_ids,
      from_stop_id || ' -> ' || to_stop_id AS path_description
    FROM pathway_network
    WHERE from_parent_station = p_station_id
      AND to_parent_station = p_station_id
      AND from_stop_id = start_stop
      AND to_stop_id != from_stop_id

    UNION ALL

    SELECT
      ps.next_stop AS current_stop,
      pr.to_stop_id AS next_stop,
      pr.pathway_id,
      pr.pathway_mode_name,
      COALESCE(pr.traversal_time, 0) AS segment_time,
      ps.total_time + COALESCE(pr.traversal_time, 0) AS total_time,
      ps.hop_count + 1 AS hop_count,
      array_append(ps.visited_stops, pr.from_stop_id) AS visited_stops,
      array_append(ps.path_ids, pr.pathway_id) AS path_ids,
      ps.path_description || ' -> ' || pr.to_stop_id AS path_description
    FROM path_search ps
    JOIN pathway_network pr
      ON ps.next_stop = pr.from_stop_id
      AND pr.from_parent_station = p_station_id
      AND pr.to_parent_station = p_station_id
      AND pr.to_stop_id != pr.from_stop_id
    WHERE ps.hop_count < max_hops
      AND NOT list_contains(ps.visited_stops, pr.to_stop_id)
  )
  SELECT
    current_stop,
    next_stop AS destination,
    total_time,
    hop_count,
    path_ids,
    visited_stops,
    path_description
  FROM path_search
  WHERE next_stop = end_stop
  ORDER BY total_time ASC, hop_count ASC
  LIMIT 1
);

-- pathfinding/find_reachable_stops
CREATE OR REPLACE MACRO find_reachable_stops(
  p_station_id VARCHAR,
  start_stop VARCHAR,
  max_time INTEGER := NULL,
  max_hops INTEGER := 5
) AS TABLE (
  WITH RECURSIVE reachability AS (
    SELECT
      to_stop_id AS reachable_stop,
      COALESCE(traversal_time, 0) AS total_time,
      1 AS hop_count,
      ARRAY[from_stop_id, to_stop_id] AS path
    FROM pathway_network
    WHERE from_parent_station = p_station_id
      AND to_parent_station = p_station_id
      AND from_stop_id = start_stop
      AND to_stop_id != from_stop_id

    UNION

    SELECT
      pr.to_stop_id AS reachable_stop,
      r.total_time + COALESCE(pr.traversal_time, 0) AS total_time,
      r.hop_count + 1 AS hop_count,
      array_append(r.path, pr.to_stop_id) AS path
    FROM reachability r
    JOIN pathway_network pr
      ON r.reachable_stop = pr.from_stop_id
      AND pr.from_parent_station = p_station_id
      AND pr.to_parent_station = p_station_id
      AND pr.to_stop_id != pr.from_stop_id
    WHERE r.hop_count < max_hops
      AND NOT list_contains(r.path, pr.to_stop_id)
      AND (max_time IS NULL OR r.total_time + COALESCE(pr.traversal_time, 0) <= max_time)
  )
  SELECT DISTINCT
    reachable_stop,
    MIN(total_time) AS min_time,
    MIN(hop_count) AS min_hops
  FROM reachability
  GROUP BY reachable_stop
  ORDER BY min_time, min_hops
);

-- pathfinding/find_all_paths
CREATE OR REPLACE MACRO find_all_paths(
  p_station_id VARCHAR,
  start_stop VARCHAR,
  end_stop VARCHAR,
  max_hops INTEGER := 5
) AS TABLE (
  WITH RECURSIVE all_paths AS (

    SELECT
      from_stop_id,
      to_stop_id,
      COALESCE(traversal_time, 0) AS total_time,
      1 AS hop_count,
      ARRAY[from_stop_id] AS visited_stops,
      ARRAY[pathway_id] AS path_ids,
      from_stop_id || ' -> ' || to_stop_id AS route
    FROM pathway_network
    WHERE from_parent_station = p_station_id
      AND to_parent_station = p_station_id
      AND from_stop_id = start_stop
      AND to_stop_id != from_stop_id

    UNION ALL

    SELECT
      ap.from_stop_id,
      pr.to_stop_id,
      ap.total_time + COALESCE(pr.traversal_time, 0) AS total_time,
      ap.hop_count + 1 AS hop_count,
      array_append(ap.visited_stops, pr.from_stop_id) AS visited_stops,
      array_append(ap.path_ids, pr.pathway_id) AS path_ids,
      ap.route || ' -> ' || pr.to_stop_id AS route
    FROM all_paths ap
    JOIN pathway_network pr
      ON ap.to_stop_id = pr.from_stop_id
      AND pr.from_parent_station = p_station_id
      AND pr.to_parent_station = p_station_id
      AND pr.to_stop_id != pr.from_stop_id
    WHERE ap.hop_count < max_hops
      AND NOT list_contains(ap.visited_stops, pr.to_stop_id)
  )
  SELECT
    total_time,
    hop_count,
    path_ids,
    route
  FROM all_paths
  WHERE to_stop_id = end_stop
  ORDER BY total_time, hop_count
);

-- pathfinding/get_direct_pathways
CREATE OR REPLACE MACRO get_direct_pathways(
  p_station_id VARCHAR,
  from_stop VARCHAR := NULL,
  to_stop VARCHAR := NULL,
  direction_filter VARCHAR := NULL,
  pathway_types VARCHAR[] := NULL
) AS TABLE (
  SELECT
    pathway_id,
    from_stop_id,
    to_stop_id,
    from_lat,
    from_lon,
    to_lat,
    to_lon,
    traversal_time,
    pathway_mode_name,
    pathway_mode,
    direction_type,
    is_bidirectional
  FROM pathway_network
  WHERE from_parent_station = p_station_id
    AND to_parent_station = p_station_id
    AND (from_stop IS NULL OR from_stop_id = from_stop)
    AND (to_stop IS NULL OR to_stop_id = to_stop)
    AND (direction_filter IS NULL OR direction_type = direction_filter)
    AND (pathway_types IS NULL OR list_contains(pathway_types, pathway_mode_name))
);

-- pathfinding/get_station_routes
CREATE OR REPLACE MACRO get_station_routes(
  p_station_id VARCHAR
) AS TABLE (
  WITH RECURSIVE shortest_paths AS (

    SELECT
      p.from_stop_id AS start_stop,
      p.to_stop_id AS end_stop,
      p.traversal_time AS total_time,
      1 AS hop_count,
      ARRAY[p.from_stop_id] AS path_stops
    FROM pathway_network p
    WHERE p.from_parent_station = p_station_id
      AND p.to_parent_station = p_station_id
      AND p.from_stop_id != p.to_stop_id
      AND p.traversal_time IS NOT NULL

    UNION

    SELECT
      sp.start_stop,
      p.to_stop_id AS end_stop,
      sp.total_time + p.traversal_time AS total_time,
      sp.hop_count + 1 AS hop_count,
      array_append(sp.path_stops, p.to_stop_id) AS path_stops
    FROM shortest_paths sp
    JOIN pathway_network p
      ON sp.end_stop = p.from_stop_id
      AND p.from_parent_station = p_station_id
      AND p.to_parent_station = p_station_id
      AND p.traversal_time IS NOT NULL
    WHERE sp.hop_count < 8
      AND p.to_stop_id != sp.start_stop
      AND NOT list_contains(sp.path_stops, p.to_stop_id)
      AND NOT EXISTS (
        SELECT 1 FROM shortest_paths sp2
        WHERE sp2.start_stop = sp.start_stop
          AND sp2.end_stop = p.to_stop_id
          AND sp2.total_time <= sp.total_time + p.traversal_time
      )
  ),

  min_paths AS (
    SELECT
      start_stop,
      end_stop,
      MIN(total_time) AS shortest_time
    FROM shortest_paths
    GROUP BY start_stop, end_stop
  ),

  null_connections AS (
    SELECT DISTINCT
      p.from_stop_id AS start_stop,
      p.to_stop_id AS end_stop,
      NULL::DOUBLE AS shortest_time
    FROM pathway_network p
    WHERE p.from_parent_station = p_station_id
      AND p.to_parent_station = p_station_id
      AND p.from_stop_id != p.to_stop_id
      AND p.traversal_time IS NULL
  ),

  all_routes AS (
    SELECT * FROM min_paths
    UNION ALL
    SELECT * FROM null_connections
    WHERE NOT EXISTS (
      SELECT 1 FROM min_paths mp
      WHERE mp.start_stop = null_connections.start_stop
        AND mp.end_stop = null_connections.end_stop
    )
  )
  SELECT
    ar.start_stop,
    ar.end_stop,
    ar.shortest_time,
    s1.location_type_name AS from_location_type_name,
    s2.location_type_name AS to_location_type_name
  FROM all_routes ar
  LEFT JOIN stops s1 ON s1.stop_id = ar.start_stop
  LEFT JOIN stops s2 ON s2.stop_id = ar.end_stop
  ORDER BY ar.start_stop, ar.end_stop
);


SELECT 'GTFS extension installed' AS status;
