// Stub for TypeScript compilation.
// Actual content generated by scripts/bundle-sql.mjs at build time,
// which overwrites dist/sql-bundle.js with the real bundle.
export const SQL_BUNDLE: Map<string, string> = new Map();
